# Generated by Django 4.1.7 on 2023-03-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_apply_now'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='apply_now',
            new_name='apply_job',
        ),
    ]
